---
# tasks file for webserver
- name: Create user
  ansible.builtin.user:
    name: "{{ webserver_user }}"

- name: Ensure httpd is installed
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Copy index.html
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.html
  notify: restart httpd

- name: Template httpd.conf
  block:
    - name: Template httpd.conf and test
      ansible.builtin.template:
        src: templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        backup: true
        validate: /usr/sbin/httpd -t -f %s
      register: template
      notify: 
        - validate httpd config
        - restart httpd
    
  rescue:
    - name: Test failed; rollback config
      ansible.builtin.copy:
        src: "{{ template.backup_file }}"
        dest: /etc/httpd/conf/httpd.conf
      notify: restart httpd
      when: template.backup_file is defined
